### ISSUE TITLE
中文路径下出现错误。

### ISSUE THREAD

**Issue by B1INGO** [PicGo/picgo-plugin-quick-capture#4]
使用插件自身一键上传出现错误。
2020-06-08 19:38:12 [PicGo INFO] [PicGo Server] is listening at 36677
2020-06-08 19:40:38 [PicGo INFO] Before transform
2020-06-08 19:40:38 [PicGo INFO] Transforming...
2020-06-08 19:40:38 [PicGo ERROR] read file C:\Users\��������\AppData\Roaming\picgo\20200608194038.png error
2020-06-08 19:40:38 [PicGo INFO] Before upload
2020-06-08 19:40:38 [PicGo INFO] Uploading...
2020-06-08 19:40:38 [PicGo SUCCESS]

**Comment by Molunerfinn** [comment]
暂时无解

**Comment by ZhidongZhou** [comment]
# A JavaScript error occurred in the main process

*** 

Uncaught Exception:
Error: spawn screencapture ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)

*** 

<img width="532" alt="z  2020-07-23 at 1902" src="https://user-images.githubusercontent.com/23629832/88269330-2ceea280-cd17-11ea-879e-8aa331c3ac5f.png">
